name: xcube-clms
channels:
  - conda-forge
dependencies:
  # Required
  - python>=3.10
  - xarray
  - cryptography
  - ipywidgets
  - requests
  - fsspec
  - xcube>=1.9.0
  - zappend
  - h5netcdf
  - boto3==1.37.3
  - libgdal-netcdf
  # Testing
  - numpy
  - black
  - flake8
  - ruff
  - pytest
  - pytest-cov
  - pytest-recording
